# Generated by Django 4.1.7 on 2023-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_user_email_otp_user_is_verified_alter_user_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
