# Generated by Django 4.1.7 on 2023-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_customerreport_invoice_wastedata_remove_user_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="email",
            field=models.CharField(max_length=255),
        ),
    ]
