# Generated by Django 4.1.7 on 2023-05-18 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_remove_history_user_remove_otp_payment_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="CreatePayment",
        ),
    ]
