# Generated by Django 4.1.7 on 2023-05-12 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_alter_message_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message",
            new_name="PickUpRequest",
        ),
    ]
