# Generated by Django 4.1.7 on 2023-05-18 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_rename_payment_createpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ConfirmingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("momo", "momo"), ("Airtel", "Airtel")], max_length=8
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "amount",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="src.createpayment",
                    ),
                ),
            ],
        ),
    ]
