# Generated by Django 4.1.7 on 2023-05-15 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0004_rename_message_pickuprequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="amount_to_pay",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.AddField(
            model_name="payment",
            name="month",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
