# Generated by Django 4.1.7 on 2023-05-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0004_alter_createpayment_user_confirmingpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmingpayment",
            name="amount",
            field=models.CharField(choices=[("2000", "2000")], max_length=8),
        ),
    ]
