# Generated by Django 4.1.7 on 2023-05-18 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0005_alter_confirmingpayment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="confirmingpayment",
            name="amount",
        ),
    ]
