# Generated by Django 4.1.7 on 2023-05-02 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0005_wastedata_waste_date_alter_client_view_cost_to_pay_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Client_View",
            new_name="ClientView",
        ),
    ]
