# Generated by Django 4.1.7 on 2023-05-04 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0006_rename_client_view_clientview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="national_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="second_number",
        ),
    ]
