# Generated by Django 4.1.7 on 2023-05-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0007_remove_payment_user_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_mode", models.CharField(max_length=50)),
                ("payment_number", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="src.payment"
                    ),
                ),
            ],
        ),
    ]
