# Generated by Django 4.1.7 on 2023-05-05 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0009_remove_profile_avatar_remove_profile_bio_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="UpdateProfile",
        ),
    ]
