# Generated by Django 4.1.7 on 2023-05-05 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0010_rename_profile_updateprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="updateprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="UpdateLocationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(blank=True, max_length=200, null=True)),
                ("district", models.CharField(blank=True, max_length=200, null=True)),
                ("sector", models.CharField(blank=True, max_length=200, null=True)),
                ("cell", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "property_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
