# Generated by Django 4.1.7 on 2023-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0011_updateprofile_email_updatelocationprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cell",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="property_number",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="province",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="sector",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
