# Generated by Django 4.1.7 on 2023-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0012_alter_user_cell_alter_user_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("Organic waste", "Organic waste"),
                    ("In Organic waste", "In Organic waste"),
                    ("Chemical waste", "Chemical waste"),
                ],
                default="Organic waste",
                max_length=200,
            ),
        ),
    ]
