# Generated by Django 4.1.7 on 2023-05-09 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0014_alter_user_waste_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="waste_type",
        ),
    ]
