# Generated by Django 4.1.7 on 2023-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0019_remove_clientview_waste_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientview",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("Organic waste", "Organic waste"),
                    ("In Organic waste", "In Organic waste"),
                    ("Chemical waste", "Chemical waste"),
                ],
                default="Organic waste",
                max_length=200,
            ),
        ),
    ]
