# Generated by Django 4.1.7 on 2023-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0020_clientview_waste_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("Organic waste", "Organic waste"),
                    ("In Organic waste", "In Organic waste"),
                    ("Chemical waste", "Chemical waste"),
                ],
                default="",
                max_length=200,
            ),
        ),
    ]
