# Generated by Django 4.1.7 on 2023-05-11 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0027_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
