# Generated by Django 4.1.7 on 2023-05-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0030_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
