# Generated by Django 4.1.7 on 2023-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0032_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
